f = open('C:/Users/11361/Documents/个人网站 3/repo/index.html', 'rb')
data = f.read()
f.close()
print('File size:', len(data))
title_pos = data.find(b'<title>')
title_close = data.find(b'</title>')
print('Title tag:', title_pos, 'to', title_close)
print('Title content:', data[title_pos+7:title_close])
body_pos = data.find(b'<body>')
body_close = data.find(b'</body>')
print('Body tag:', body_pos, 'to', body_close)
print('Body length:', body_close - body_pos - 6)
script_pos = data.find(b'<script>')
script_close = data.find(b'</script>')
print('Script tag:', script_pos, 'to', script_close)
head_close = data.find(b'</head>')
print('Head close:', head_close)
